//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS_PatEditor.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditorFormCodeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorFormCodeRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GS_PatEditor.Localization.EditorFormCodeRes", typeof(EditorFormCodeRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully exported to last location. 的本地化字符串。
        /// </summary>
        internal static string AutoExportFinished {
            get {
                return ResourceManager.GetString("AutoExportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new key frame? 的本地化字符串。
        /// </summary>
        internal static string CreateKeyFrameConfirm {
            get {
                return ResourceManager.GetString("CreateKeyFrameConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown file format. 的本地化字符串。
        /// </summary>
        internal static string ErrorUnknownProjectFormat {
            get {
                return ResourceManager.GetString("ErrorUnknownProjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save the project before exit? 的本地化字符串。
        /// </summary>
        internal static string ExitConfirm {
            get {
                return ResourceManager.GetString("ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imported  的本地化字符串。
        /// </summary>
        internal static string ImportedAnimationPrefix {
            get {
                return ResourceManager.GetString("ImportedAnimationPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AnimationEditor 的本地化字符串。
        /// </summary>
        internal static string MsgBoxTitle {
            get {
                return ResourceManager.GetString("MsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new act project? 的本地化字符串。
        /// </summary>
        internal static string NewProjectConfirm {
            get {
                return ResourceManager.GetString("NewProjectConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open an act project? 的本地化字符串。
        /// </summary>
        internal static string OpenProjectConfirm {
            get {
                return ResourceManager.GetString("OpenProjectConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the action? 的本地化字符串。
        /// </summary>
        internal static string RemoveActionConfirm {
            get {
                return ResourceManager.GetString("RemoveActionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove exporter? 的本地化字符串。
        /// </summary>
        internal static string RemoveExporterConfirm {
            get {
                return ResourceManager.GetString("RemoveExporterConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove this key frame? The damage and cancellable data will be lost. 的本地化字符串。
        /// </summary>
        internal static string RemoveKeyFrameConfirm {
            get {
                return ResourceManager.GetString("RemoveKeyFrameConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
    }
}
