//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS_PatEditor.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditorFormCodeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorFormCodeRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GS_PatEditor.Localization.EditorFormCodeRes", typeof(EditorFormCodeRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align all frames in this segment?.
        /// </summary>
        internal static string AlignAllFramesConfirm {
            get {
                return ResourceManager.GetString("AlignAllFramesConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to last location..
        /// </summary>
        internal static string AutoExportFinished {
            get {
                return ResourceManager.GetString("AutoExportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} frames fixed, {1} frames remain empty..
        /// </summary>
        internal static string CloneHitBoxResult {
            get {
                return ResourceManager.GetString("CloneHitBoxResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the action?.
        /// </summary>
        internal static string CopyActionConfirm {
            get {
                return ResourceManager.GetString("CopyActionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new key frame?.
        /// </summary>
        internal static string CreateKeyFrameConfirm {
            get {
                return ResourceManager.GetString("CreateKeyFrameConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file format..
        /// </summary>
        internal static string ErrorUnknownProjectFormat {
            get {
                return ResourceManager.GetString("ErrorUnknownProjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the project before exit?.
        /// </summary>
        internal static string ExitConfirm {
            get {
                return ResourceManager.GetString("ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported .
        /// </summary>
        internal static string ImportedAnimationPrefix {
            get {
                return ResourceManager.GetString("ImportedAnimationPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnimationEditor.
        /// </summary>
        internal static string MsgBoxTitle {
            get {
                return ResourceManager.GetString("MsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new act project?.
        /// </summary>
        internal static string NewProjectConfirm {
            get {
                return ResourceManager.GetString("NewProjectConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an act project?.
        /// </summary>
        internal static string OpenProjectConfirm {
            get {
                return ResourceManager.GetString("OpenProjectConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the action?.
        /// </summary>
        internal static string RemoveActionConfirm {
            get {
                return ResourceManager.GetString("RemoveActionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove exporter?.
        /// </summary>
        internal static string RemoveExporterConfirm {
            get {
                return ResourceManager.GetString("RemoveExporterConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this key frame? The damage and cancellable data will be lost..
        /// </summary>
        internal static string RemoveKeyFrameConfirm {
            get {
                return ResourceManager.GetString("RemoveKeyFrameConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
    }
}
