//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS_PatEditor.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormCodeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormCodeRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GS_PatEditor.Localization.FormCodeRes", typeof(FormCodeRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Segment {0}, Frame {1} 的本地化字符串。
        /// </summary>
        internal static string FrameReferenceEditForm_ListFormat {
            get {
                return ResourceManager.GetString("FrameReferenceEditForm_ListFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string FrameReferenceEditForm_ListUnknown {
            get {
                return ResourceManager.GetString("FrameReferenceEditForm_ListUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Import 的本地化字符串。
        /// </summary>
        internal static string ImageSelectForm_BatchImport {
            get {
                return ResourceManager.GetString("ImageSelectForm_BatchImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new image? 的本地化字符串。
        /// </summary>
        internal static string ImageSelectForm_ConfirmCreate {
            get {
                return ResourceManager.GetString("ImageSelectForm_ConfirmCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to remove this image from project? You can add it later if you still need it. 的本地化字符串。
        /// </summary>
        internal static string ImageSelectForm_ConfirmRemove {
            get {
                return ResourceManager.GetString("ImageSelectForm_ConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;create&gt; 的本地化字符串。
        /// </summary>
        internal static string ImageSelectForm_CreateItem {
            get {
                return ResourceManager.GetString("ImageSelectForm_CreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string ImageSelectForm_Import {
            get {
                return ResourceManager.GetString("ImageSelectForm_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Select 的本地化字符串。
        /// </summary>
        internal static string ImageSelectForm_MsgBoxTitle {
            get {
                return ResourceManager.GetString("ImageSelectForm_MsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose an existing image. 的本地化字符串。
        /// </summary>
        internal static string ImageSelectForm_NotCreated {
            get {
                return ResourceManager.GetString("ImageSelectForm_NotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This image is in use. 的本地化字符串。
        /// </summary>
        internal static string ImageSelectForm_RemoveInUse {
            get {
                return ResourceManager.GetString("ImageSelectForm_RemoveInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Animation {0} 的本地化字符串。
        /// </summary>
        internal static string ImportPatAnimationForm_ListFormat {
            get {
                return ResourceManager.GetString("ImportPatAnimationForm_ListFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Animation {0}, Segment {1} 的本地化字符串。
        /// </summary>
        internal static string ImportPatAnimationForm_ListFormatFollower {
            get {
                return ResourceManager.GetString("ImportPatAnimationForm_ListFormatFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Animation 的本地化字符串。
        /// </summary>
        internal static string ImportPatAnimationForm_MsgBoxTitle {
            get {
                return ResourceManager.GetString("ImportPatAnimationForm_MsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Palette file not found. Please choose one. 的本地化字符串。
        /// </summary>
        internal static string ImportPatAnimationForm_PaletteNotFound {
            get {
                return ResourceManager.GetString("ImportPatAnimationForm_PaletteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 imported_ 的本地化字符串。
        /// </summary>
        internal static string ImportPatAnimationForm_ProjPath {
            get {
                return ResourceManager.GetString("ImportPatAnimationForm_ProjPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 imported_palette_ 的本地化字符串。
        /// </summary>
        internal static string ImportPatAnimationForm_ProjPathPal {
            get {
                return ResourceManager.GetString("ImportPatAnimationForm_ProjPathPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewDirectory 的本地化字符串。
        /// </summary>
        internal static string ProjectDirectoryEditForm_FreeNamePrefix {
            get {
                return ResourceManager.GetString("ProjectDirectoryEditForm_FreeNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Recent List 的本地化字符串。
        /// </summary>
        internal static string RecentFileList_Save {
            get {
                return ResourceManager.GetString("RecentFileList_Save", resourceCulture);
            }
        }
    }
}
