//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS_PatEditor.Localization.Elements {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClassNameRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassNameRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GS_PatEditor.Localization.Elements.ClassNameRes", typeof(ClassNameRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bullet_Init 的本地化字符串。
        /// </summary>
        internal static string BulletInitBehavior {
            get {
                return ResourceManager.GetString("BulletInitBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClearFollowingEffect 的本地化字符串。
        /// </summary>
        internal static string ClearFollowingEffectBehavior {
            get {
                return ResourceManager.GetString("ClearFollowingEffectBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateBullet 的本地化字符串。
        /// </summary>
        internal static string CreateBulletBehavior {
            get {
                return ResourceManager.GetString("CreateBulletBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinishAfter 的本地化字符串。
        /// </summary>
        internal static string EffectActorBehaviorEntryFinisheAfter {
            get {
                return ResourceManager.GetString("EffectActorBehaviorEntryFinisheAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash 的本地化字符串。
        /// </summary>
        internal static string EffectActorBehaviorEntryFlash {
            get {
                return ResourceManager.GetString("EffectActorBehaviorEntryFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IncreaseAlpha 的本地化字符串。
        /// </summary>
        internal static string EffectActorBehaviorEntryIncreaseAlpha {
            get {
                return ResourceManager.GetString("EffectActorBehaviorEntryIncreaseAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitRandomRotation 的本地化字符串。
        /// </summary>
        internal static string EffectActorBehaviorEntryInitRandomRotation {
            get {
                return ResourceManager.GetString("EffectActorBehaviorEntryInitRandomRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitRandomScale 的本地化字符串。
        /// </summary>
        internal static string EffectActorBehaviorEntryInitRandomScale {
            get {
                return ResourceManager.GetString("EffectActorBehaviorEntryInitRandomScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RandomReverseY 的本地化字符串。
        /// </summary>
        internal static string EffectActorBehaviorEntryRandomReverseY {
            get {
                return ResourceManager.GetString("EffectActorBehaviorEntryRandomReverseY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReduceAlpha 的本地化字符串。
        /// </summary>
        internal static string EffectActorBehaviorEntryReduceAlpha {
            get {
                return ResourceManager.GetString("EffectActorBehaviorEntryReduceAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReduceScaleRatio 的本地化字符串。
        /// </summary>
        internal static string EffectActorBehaviorEntryReduceScaleRatio {
            get {
                return ResourceManager.GetString("EffectActorBehaviorEntryReduceScaleRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual 的本地化字符串。
        /// </summary>
        internal static string EffectBehavior {
            get {
                return ResourceManager.GetString("EffectBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effect_FollowParent 的本地化字符串。
        /// </summary>
        internal static string EffectFollowParentBehavior {
            get {
                return ResourceManager.GetString("EffectFollowParentBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effect_Init 的本地化字符串。
        /// </summary>
        internal static string EffectInitBehavior {
            get {
                return ResourceManager.GetString("EffectInitBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effect_Segment 的本地化字符串。
        /// </summary>
        internal static string EffectSegmentBehavior {
            get {
                return ResourceManager.GetString("EffectSegmentBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FrameSinglePoint 的本地化字符串。
        /// </summary>
        internal static string FrameSinglePointProvider {
            get {
                return ResourceManager.GetString("FrameSinglePointProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player_HoldSkill 的本地化字符串。
        /// </summary>
        internal static string HoldSkillBehavior {
            get {
                return ResourceManager.GetString("HoldSkillBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inherit 的本地化字符串。
        /// </summary>
        internal static string InheritBehavior {
            get {
                return ResourceManager.GetString("InheritBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JumpSegment 的本地化字符串。
        /// </summary>
        internal static string JumpSegmentBehavior {
            get {
                return ResourceManager.GetString("JumpSegmentBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player_AirSpeed 的本地化字符串。
        /// </summary>
        internal static string PlayerAirSpeedCtrlBehavior {
            get {
                return ResourceManager.GetString("PlayerAirSpeedCtrlBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AirJump 的本地化字符串。
        /// </summary>
        internal static string PlayerAirSpeedCtrlBehaviorEntryAirJump {
            get {
                return ResourceManager.GetString("PlayerAirSpeedCtrlBehaviorEntryAirJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gravity 的本地化字符串。
        /// </summary>
        internal static string PlayerAirSpeedCtrlBehaviorEntryGravity {
            get {
                return ResourceManager.GetString("PlayerAirSpeedCtrlBehaviorEntryGravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recoil 的本地化字符串。
        /// </summary>
        internal static string PlayerAirSpeedCtrlBehaviorEntryRecoil {
            get {
                return ResourceManager.GetString("PlayerAirSpeedCtrlBehaviorEntryRecoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReduceSpeed 的本地化字符串。
        /// </summary>
        internal static string PlayerAirSpeedCtrlBehaviorEntryReduceSpeed {
            get {
                return ResourceManager.GetString("PlayerAirSpeedCtrlBehaviorEntryReduceSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player_GroundSpeed 的本地化字符串。
        /// </summary>
        internal static string PlayerGroundSpeedCtrlBehavior {
            get {
                return ResourceManager.GetString("PlayerGroundSpeedCtrlBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friction 的本地化字符串。
        /// </summary>
        internal static string PlayerGroundSpeedCtrlBehaviorEntryFriction {
            get {
                return ResourceManager.GetString("PlayerGroundSpeedCtrlBehaviorEntryFriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jump 的本地化字符串。
        /// </summary>
        internal static string PlayerGroundSpeedCtrlBehaviorEntryJump {
            get {
                return ResourceManager.GetString("PlayerGroundSpeedCtrlBehaviorEntryJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recoil 的本地化字符串。
        /// </summary>
        internal static string PlayerGroundSpeedCtrlBehaviorEntryRecoil {
            get {
                return ResourceManager.GetString("PlayerGroundSpeedCtrlBehaviorEntryRecoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player_AirSkillInit 的本地化字符串。
        /// </summary>
        internal static string PlayerSkillAirBehavior {
            get {
                return ResourceManager.GetString("PlayerSkillAirBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player_GroundSkillInit 的本地化字符串。
        /// </summary>
        internal static string PlayerSkillGroundBehavior {
            get {
                return ResourceManager.GetString("PlayerSkillGroundBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player_LoopBreak 的本地化字符串。
        /// </summary>
        internal static string PlayerSkillLoopBreakBehavior {
            get {
                return ResourceManager.GetString("PlayerSkillLoopBreakBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player_SystemAnimationInit 的本地化字符串。
        /// </summary>
        internal static string PlayerSystemAnimationBehavior {
            get {
                return ResourceManager.GetString("PlayerSystemAnimationBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlaySoundEffect 的本地化字符串。
        /// </summary>
        internal static string PlaySoundEffectBehavior {
            get {
                return ResourceManager.GetString("PlaySoundEffectBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndOfSegment 的本地化字符串。
        /// </summary>
        internal static string TimeEndSegment {
            get {
                return ResourceManager.GetString("TimeEndSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RepeatInSegment 的本地化字符串。
        /// </summary>
        internal static string TimeRepeat {
            get {
                return ResourceManager.GetString("TimeRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartOfSegment 的本地化字符串。
        /// </summary>
        internal static string TimeStartSegment {
            get {
                return ResourceManager.GetString("TimeStartSegment", resourceCulture);
            }
        }
    }
}
